name: Build on Windows MSYS2 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MSYS2-build-and-test:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: git make patch unzip mingw-w64-ucrt-x86_64-toolchain mingw-w64-ucrt-x86_64-zlib mingw-w64-ucrt-x86_64-gmp
    - uses: actions/checkout@v4
    - name: clone COMiniSatPS
      run: |
        cd ..
        git clone https://github.com/marekpiotrow/cominisatps
        cd cominisatps
        rm core simp mtl utils
        ln -s minisat/core minisat/simp minisat/mtl minisat/utils .
    - name: build CaDiCaL
      run: |
        cd ..
        git clone https://github.com/arminbiere/cadical
        cd cadical
        patch -p1 <../uwrmaxsat/cadical.patch
        ./configure
        make cadical
    - name: build the MaxPre preprocessor
      run: |
        cd ..
        git clone https://github.com/Laakeri/maxpre
        cd maxpre
        sed -i 's/-g/-D NDEBUG/' src/Makefile
        make lib
    - name: build UWrMaxSat
      run: |
        make config
        USESCIP= make r
    - name: test executable
      run: |
        set +e
        build/release/bin/uwrmaxsat -of Examples/unsat.opb
        if ! [ $? -eq 20 ] ; then exit 1 ; fi
        build/release/bin/uwrmaxsat -of Examples/garden9x9.opb
        if ! [ $? -eq 30 ] ; then exit 1 ; fi
        build/release/bin/uwrmaxsat -bm Examples/satellite02ac.wcsp.wcnf
        if ! [ $? -eq 30 ] ; then exit 1 ; fi
        build/release/bin/uwrmaxsat -maxpre -bm Examples/satellite02ac.wcsp.wcnf
        if ! [ $? -eq 30 ] ; then exit 1 ; fi
    - name: build and test BIGWEIGHTS  
      run: |
        USESCIP= make clean
        sed -i 's/BIGWEIGHTS?=#/BIGWEIGHTS?=/' config.mk
        USESCIP= make r
        set +e
        build/release/bin/uwrmaxsat -of Examples/stein27_bignum.opb
        if ! [ $? -eq 30 ] ; then exit 1 ; fi
